### ISSUE TITLE
Support for iOS?

### ISSUE THREAD

**Issue by bhushangawde** [cardona/SwiftMistralCoreML-DemoApp#12]
Hello @cardona 

Is there any plan to support for iOS.?

Currently, when I try to run the app for iOS 18.0 emulator, it does not work.

**Comment by cardona** [comment]
Hi @bhushangawde 

The application should work on iOS 18 or later, but it has specific hardware requirements: it is only compatible with the iPhone 15 Pro and newer devices due to its reliance on advanced hardware features like MPSGraph and Metal Performance Shaders (MPS), which are not available on older models or the iOS simulator.

Currently, the iOS simulator does not support these features because it lacks access to GPU hardware. Although the model works perfectly on macOS, I have not been able to verify its functionality because my iPhone is an older model.

Theoretically, the application should run as expected on compatible devices.
